### ISSUE TITLE
Support HTTP(s) proxy server 

### ISSUE THREAD

**Issue by FlorentinDUBOIS** [CleverCloud/clever-operator#48]
Hey :wave:,

It could be interesting to support proxy server at least using the following environment variables:
- `HTTP_PROXY`
- `HTTPS_PROXY`
- `NO_PROXY`

It should be also possible to configure those variables through the operator's configuration file. Below, you will find an example of what it could be:

```toml
[proxy]
http = ["example.com"]
https = ["example.com"]
none = ["example.com", "127.0.0.1"]
basic = { user = "John Doe", password = "itisasecret" } # optional
token = "a bearer token" # optional
```

There is some examples of configuration on the [ArchWiki](https://wiki.archlinux.org/title/Proxy_server#Environment_variables).

I also so a library that could help to do the work.

https://github.com/tafia/hyper-proxy
