### ISSUE TITLE
Investigate how to integrate applications

### ISSUE THREAD

**Issue by FlorentinDUBOIS** [CleverCloud/clever-operator#63]
Hey :wave:,

It could be great to integrate applications as a Custom Resource in the operator. Based on the [OpenAPI schema](https://api.clever-cloud.com/v2/openapi.json) of the Clever Cloud API, we could create an application quite easily. The definition of the payload is named `WannaBeApplication`.

Then, we need to push a commit to this newly created repository. This could be achieved using a trick that works at Clever Cloud by using oauth consumer credentials in the git remote http url of the repository.

The Custom Resource could seems like below.

```yaml
---
apiVersion: api.clever-cloud.com/v1beta1
kind: Runtime
metadata:
  namespace: default
  name: my-app-0
  annotations:
    api.clever-cloud.com/description: ''
    api.clever-cloud.com/tag: ''
spec:
  organisation: orga_xxxx
  runtime:
    kind: rust
  deployment:
    environment:
      PORT: 8080
    region: par
    options:
      interrupt: true
      force_https: true
      session_affinity: true
    build:
      cancel_on_push: true
      dedicated: M
    dependencies:
    - postgres_xxx
    - app_xxx
  scalability:
    horizontal:
      min: 1
      max: 1
    vertical:
      min: pico
      max: 3xl
  domain:
    customs:
    - my-app-0.cleverapps.io
...
```
